---

- name: Upgrade all packages
  yum:
    name: "*"
    state: latest
    
  when: keep_packages_updated == true

- name: Install some packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - smartmontools
    - htop
    - zfs
    - bonnie++
    - unzip
    - lm-sensors

#  - name: Configure smartmontools

- name: "Set hostname to {{ ansible_nas_hostname }}"
  hostname:
    name: "{{ ansible_nas_hostname }}"
